### ISSUE TITLE
Inconsistency with tricks.py

### ISSUE THREAD

**Issue by gottstaff** [remicres/otbtf_tutorials#1]
I'm using the docker image to check the first example "create_model1.py" and found the function CreateSavedModel() called in line 59 is defined as create_savedmodel() in tricks.py.
Cheers

**Comment by remicres** [comment]
Thanks. `CreateSavedModel()` is deprecated since a few commits, I'll correct it here!

**Comment by remicres** [comment]
I have corrected this in otbtf (`develop` branch, also in the docker images). Let me know if you still encounter this issue
