### ISSUE TITLE
Running the script create_model1.py on python fail

### ISSUE THREAD

**Issue by nitcheulegrand** [remicres/otbtf_tutorials#2]
I'm using the docker image to check the first example "create_model1.py" and found the following Error while running the script.
```
ModuleNotFoundError: No module named 'tricks'
```
I install tricks module by running 
```sh
docker run -i -t -u root -v $(pwd):/data mdl4eo/otbtf1.7:gpu /bin/sh
pip install tricks
python /data/scripts/model1.py /data/results/SavedModel_cnn
```
It still fail with the same error.
Can you please give me any solution about this?
Thanks in advance!

**Comment by remicres** [comment]
Hi @nitcheulegrand ,
Using the (old) version 1.7, you have to update manually the `PYTHONPATH` environment variable, adding the path to the `tricks.py` of otbtf.
I believe that the following command will do the work:
```
export PYTHONPATH=$PYTHONPATH:/work/otb/otb/Modules/Remote/otbtf/python/
```

And don't run `pip install tricks`: "tricks" is just a module of otbtf (it will be removed soon, replaced with... otbtf :wink: )

Maybe using more recent docker images can be more straightforward! We did some work to ease the use.

Hope that helps

**Comment by nitcheulegrand** [comment]
Thanks for reply @remicres .
It's sure that I need to use the most recent version. Because I continue have error. Now it's the following :
```
Traceback (most recent call last):
  File "scripts/model1.py", line 59, in <module>
    create_savedmodel(sess, ["x:0", "y:0"], ["features:0", "prediction:0"], sys.argv[1])
NameError: name 'create_savedmodel' is not defined
```
I did not run `pip install tricks`.
Should I install any module or make any other configuration for this to function ?

**Comment by nitcheulegrand** [comment]
I resolved it using by replacing the `create_savemodel` by `CreateSaveModel` referring to the issue https://github.com/remicres/otbtf_tutorials_resources/issues/1
Thanks for assistance !
